version: "3.9"
services:

  frontend:
    image: affinityplm/impactanalysis-frontend:0.1
    ports:
      - "3000:3000"
    volumes:
      - ./configurations:/app/src/configurations

  backend:
    image: affinityplm/impactanalysis-backend:0.1
    ports:
      - "8000:80"
    volumes:
      - ./configurations:/configurations
    secrets:
      - source: credentials
        target: "credentials.txt"

  mongo:
      image: mongo
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: "root"
        MONGO_INITDB_ROOT_PASSWORD: "example"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "example"

secrets:
  credentials:
    external: true