version: "3.9"
services:

  frontend:
    image: affinityplm/impactanalysis-frontend:0.1
    ports:
      - "3000:3000"
    volumes:
      - ./configurations:/app/src/configurations

  backend:
    image: affinityplm/impactanalysis-backend:0.1
    ports:
      - "8000:80"
    volumes:
      - ./configurations:/configurations
    secrets:
      - database-credentials.txt
      - windchill-credentials.txt      

  mongo:
      image: mongo
      ports:
        - "27017:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: "root"
        MONGO_INITDB_ROOT_PASSWORD: "example"

secrets:
  database-credentials.txt:
    external: true
  windchill-credentials.txt:
    external: true
